{pkgs}: {
  deps = [
    pkgs.xorg.libxkbfile
    pkgs.libglvnd
    pkgs.mesa
    pkgs.xorg.libxshmfence
    pkgs.libxkbcommon
    pkgs.alsa-lib
    pkgs.at-spi2-core
    pkgs.at-spi2-atk
    pkgs.gdk-pixbuf
    pkgs.cairo
    pkgs.pango
    pkgs.gtk3
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libX11
    pkgs.xorg.libxcb
    pkgs.nspr
    pkgs.cups
    pkgs.nss
    pkgs.atk
    pkgs.dbus
    pkgs.glib
    pkgs.jq
    pkgs.postgresql
    pkgs.geckodriver
    pkgs.firefox-esr
    pkgs.chromium
    pkgs.zip
  ];
}
